// RTL file list, package first. Consumed by lint and by the Verilator build.
../rtl/pkg/coh_pkg.sv
../rtl/lib/reset_sync.sv
../rtl/lib/rr_arbiter.sv
../rtl/lib/credit_counter.sv
../rtl/lib/fifo.sv
../rtl/lib/skid_buffer.sv
../rtl/lib/sram_1rw.sv
../rtl/noc/route_compute.sv
../rtl/noc/input_unit.sv
../rtl/noc/vc_allocator.sv
../rtl/noc/switch_allocator.sv
../rtl/noc/crossbar.sv
../rtl/noc/router.sv
../rtl/noc/noc_top.sv
../rtl/mem/mem_model.sv
../rtl/l1/mshr_file.sv
../rtl/l1/l1_coh_fsm.sv
../rtl/l2/dir_coh_fsm.sv
../rtl/l1/l1_cache.sv
../rtl/l2/l2_bank.sv
../rtl/l2/tbe_file.sv
../rtl/l2/dir_ctrl.sv
../rtl/top/system_top.sv
