#!/usr/bin/env python3
"""Make the SRAM black boxes linkable by OpenSTA, without inventing timing.

yosys writes a black-box instance with its parameters attached:

    sram_1rw #(.DEPTH(32'd64), .WIDTH(32'd256)) \\u_l2.gen_way[0].u_data (...)

OpenSTA's Verilog reader does not accept the `#(...)`, and even if it did, one
Liberty cell cannot describe instances whose bus widths differ -- and they do:
the tag arrays are narrow, the data arrays are a whole cache line.

So each instance is renamed to a cell named after its configuration,
`sram_1rw_W256_D64`, and a Liberty is emitted with one cell per configuration:
pin directions, a nominal input capacitance, and NOTHING ELSE.

No timing arcs. That is the point, and it is the same position decision D25
argues for the Design Compiler flow: this project has no memory compiler, so
the array's access time is not known, and a hand-written number would produce
a timing report that looks signed off and is not. Paths into the address and
write-data pins, and out of the read-data pins, are budgeted in
syn/yosys/sta.tcl with `set_max_delay` -- so they are timed, and the array
itself is visibly absent rather than invisibly free.

Usage: blackbox_lib.py <netlist.v> <out.lib>   (rewrites the netlist in place)
"""
import math
import re
import sys

# `sram_1rw #( .DEPTH(32'd64), .WIDTH(32'd256) ) <instance> (`
# The parameter list itself contains parentheses -- `.DEPTH(32'd64)` -- so the
# body is matched as "anything but parens, or one balanced pair", not as
# "anything but a close paren".
INST = re.compile(
    r"\b(?P<mod>[A-Za-z_][\w$]*)\s*#\s*\("
    r"(?P<params>(?:[^()]|\([^()]*\))*)"
    r"\)\s*(?P<inst>\\\S+|[A-Za-z_][\w$]*)\s*\(", re.S)
PARAM = re.compile(r"\.(\w+)\s*\(\s*\d+'d(\d+)\s*\)")

# Port directions, by name suffix. This design's naming convention is strict
# and check_style.sh enforces it, which is what makes this safe.
def direction(pin):
    return "output" if pin.endswith("_o") else "input"


def cell_name(mod, params):
    bits = "_".join(f"{k[0].upper()}{v}" for k, v in sorted(params.items()))
    return f"{mod}_{bits}"


def widths(params):
    """Bus widths for this design's SRAM wrapper, from its parameters."""
    w = params.get("WIDTH", 32)
    d = params.get("DEPTH", 64)
    abits = max(1, int(math.ceil(math.log2(d))) if d > 1 else 1)
    return {"addr_i": abits, "wdata_i": w, "rdata_o": w}


def main(netlist, out_lib):
    text = open(netlist).read()
    configs = {}

    def rewrite(m):
        params = {k: int(v) for k, v in PARAM.findall(m.group("params"))}
        if not params:
            return m.group(0)
        name = cell_name(m.group("mod"), params)
        configs[name] = params
        # An escaped identifier is terminated by whitespace, so the space
        # after it is part of the name and must survive the rewrite.
        return f"{name} {m.group('inst')} ("

    new = INST.sub(rewrite, text)
    if not configs:
        return 0
    open(netlist, "w").write(new)

    types, cells = [], []
    seen_types = set()
    for name, params in sorted(configs.items()):
        bus = widths(params)
        for w in set(bus.values()):
            t = f"bus_{w}"
            if t not in seen_types:
                seen_types.add(t)
                types.append(
                    f"  type ({t}) {{\n"
                    f"    base_type : array; data_type : bit;\n"
                    f"    bit_width : {w}; bit_from : {w - 1}; bit_to : 0;\n"
                    f"    downto : true;\n  }}")
        pins = ["  cell (%s) {" % name,
                "    area : 0.0;",
                "    pin (clk) { direction : input; clock : true; "
                "capacitance : 0.001; }",
                "    pin (en_i) { direction : input; capacitance : 0.001; }",
                "    pin (we_i) { direction : input; capacitance : 0.001; }"]
        for pin, w in sorted(bus.items()):
            d = direction(pin)
            cap = "" if d == "output" else " capacitance : 0.001;"
            pins.append(f"    bus ({pin}) {{ bus_type : bus_{w}; "
                        f"direction : {d};{cap} }}")
        pins.append("  }")
        cells.append("\n".join(pins))

    with open(out_lib, "w") as f:
        f.write(
            "/* Generated by syn/yosys/blackbox_lib.py -- DO NOT hand-edit.\n"
            "   Pin directions only. No timing arcs, deliberately: see the\n"
            "   script header and decision D25. */\n"
            "library (coherent_noc_blackboxes) {\n"
            "  technology (cmos);\n"
            "  delay_model : table_lookup;\n"
            "  time_unit : \"1ps\";\n"
            "  voltage_unit : \"1V\";\n"
            "  current_unit : \"1uA\";\n"
            "  capacitive_load_unit (1, ff);\n"
            "  pulling_resistance_unit : \"1kohm\";\n"
            "  leakage_power_unit : \"1pW\";\n"
            "  default_max_transition : 320;\n"
            + "\n".join(types) + "\n"
            + "\n".join(cells) + "\n}\n")
    print(f"{out_lib}: {len(configs)} black-box cell(s) "
          f"({', '.join(sorted(configs))})")
    return len(configs)


if __name__ == "__main__":
    sys.exit(0 if main(sys.argv[1], sys.argv[2]) >= 0 else 1)
